[package]
name = "milk"
version = "0.0.1"
authors = ["John Weachock <jweachock@gmail.com>"]

[dependencies]
clap = "2.30.0"
git2 = "0.6.11"

[[bin]]
name = "milk"
path = "src/main.rs"

[[bin]]
name = "milk-init"
path = "src/init.rs"

[[bin]]
name = "milk-clone"
path = "src/clone.rs"
