[package]
name = "milk"
version = "0.0.1"
authors = ["John Weachock <jweachock@gmail.com>"]

[dependencies]
clap = "2.30.0"

[[bin]]
name = "milk"
path = "src/main.rs"

[[bin]]
name = "milk-init"
path = "src/init.rs"
